Made it possible to pass variables to the dev template via settings.
rocjs/roc-package-web-component pull request #8
Opened 2016-10-11 13:16 UTC by Naycon

This pull request adds a setting for passing additional template variables to the nunjuck template the dev server uses. One use case for this is to be able to set secrets not suitable for version control in the shell environment for developers and pass them into the demo this way.

2016-10-11 13:45 UTC, dlmr requested changes

2016-10-11 13:45 UTC, dlmr commented on extensions/roc-package-web-component-dev/src/commands/nunjucks.js
> +        const templateVariables = Object.assign({
Can we use the following syntax here?
```js
{
  name,
  bundlePath: stats.script,
  ...template.variables
}
```

2016-10-11 13:45 UTC, dlmr commented on extensions/roc-package-web-component-dev/src/config/roc.config.meta.js
> +                    description: 'An array of variables to expose to the dev template. Will be merged with the default template variables.',
Should probably be `An object...` here.

2016-10-11 14:07 UTC, dlmr commented on extensions/roc-package-web-component-dev/src/commands/nunjucks.js
> +            ...template.variables,
Might it be better here to place all user defined variables under a single property? Like `userVariables` for example.

2016-10-11 14:08 UTC, dlmr commented
Could we add how this new functionality can be used by updating the example?

2016-10-11 14:09 UTC, dlmr approved these changes

2016-10-11 14:20 UTC, Naycon commented
Sure, will add an example on usage!

2016-10-12 18:04 UTC, dlmr commented
Thanks! This looks good! 👍 

The only thing is that we now get warnings in the example for properties that Roc does not understand since Roc handles `settings` in a managed way. What I'm not trying to decide is how we should handle this case and similar ones that we will have in the future, we should definitely not get warnings at least. I see a couple of different options and I'm glad for feedback and other ideas.

1. Recommend that "custom" config values are used when using this type of generic objects.
2. Change the way the validation works to not get a warning here, for example if the object is empty from the extensions. The only problem with this is that it will not work great if another extension composes such a setting since it will then become managed and give warnings for the user provided values.
3. Use a new form of meta data to tell Roc that this object should be used as a generic value and not as a normal managed value. This is kinda the same thing as the custom alternative mentioned in 1. 

With this said I think we should hold off of merging this until we have decided the best approach.

2016-10-14 07:25 UTC, Naycon commented
You're welcome! Makes sense @dlmr to hold off until a way forward regarding the config has been decided.

Regarding option 2, what do you mean by 'if another extension composes such a setting'?

2016-10-15 19:02 UTC, dlmr commented
@Naycon An example of this would be if a `roc-package-web-component-react` would define a value on `settings.dev.template.customValues`.

2016-10-15 21:08 UTC, dlmr commented
A suggestion is to update the `isObject` validator to allow it not validate nested keys using a new second argument:
```js
isObject(true);
isObject(validator, true);
```
Using such a validator will not give warnings on mismatched keys and also allow other extensions to add keys. 

What do you think about this @Naycon?

2016-10-17 07:37 UTC, Naycon commented
@dlmr - So if I define a new key in `roc-package-web-component-react` on that object with a validator, that would give me warnings for that setting if it is of the wrong type, but it would not give warnings if I define some custom keys as a user? If so, that would work. Maybe use an options object instead of just `true` as the final argument, to make it more future proof if you need to add similar solutions in the future?

2016-10-17 07:58 UTC, dlmr commented
@Naycon Correct.

2016-10-23 14:09 UTC, dlmr commented
I have now published a new version of `roc` that supports marking an object as _unmanaged_, `1.0.0-rc.14`. 

[Read more about the new option here.](https://github.com/rocjs/roc/blob/master/docs/Validators.md#isobject)

So you should be able to update the PR to use this new option and we can after that go ahead and merge this. 🙂

2016-10-28 08:12 UTC, Naycon commented
Thanks @dlmr! I updated the PR to use the new isObject option and bumped the version of the roc dependency.

2016-10-28 08:21 UTC, dlmr commented
Great stuff! 👍

2016-10-28 08:22 UTC, merged

2016-10-28 08:27 UTC, dlmr commented
Released as `1.0.0-beta.3` 🎉

2016-10-28 08:39 UTC, Naycon commented
🎉